-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjxyWo3+jlB1s3LkQ
lIASWuHkufT+dRkC+NJ9TjfiecGgCgYIKoZIzj0DAQehRANCAASgMMx0IjG52p1J
E99yTIWftDBHv60cWLyYYMWBqkw2vR9SXXreiEZVxAWKDqt8DCAgajFIqZrZjmV4
8SWQA+4W
-----END PRIVATE KEY-----